name: Build iOS IPA

on:
  workflow_dispatch: # Permet de lancer la compilation manuellement en 1 clic
  push:
    branches: [ main, master ]

jobs:
  build-ios:
    name: Build iOS (.ipa)
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS App (.ipa)
        run: |
          flutter build ios --release --no-codesign
          mkdir -p build/ios/ipa/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -r ChatMe.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ChatMe-iOS-IPA
          path: build/ios/ipa/ChatMe.ipa
          retention-days: 14

